<?php
// @codingStandardsIgnoreFile
use Xtento\CustomAttributes\Api\Data\FieldsInterface;
use Xtento\CustomAttributes\Block\Customer\Widget\Text;
use Xtento\CustomAttributes\Helper\Data;
use Xtento\CustomAttributes\Model\Sources\InputType;

/** @var Text $block */
$field = $block->getField();
$attribute = $field->getData(Data::ATTRIBUTE_DATA);
?>
<?php if ($field->getFrontendInput() === InputType::TEXT): ?>
    <?php
    $attributeCode = $attribute->getData(FieldsInterface::ATTRIBUTE_CODE);
    $attributeLabel = $attribute->getStoreLabel();
    $value = $block->customAttributeValue($attributeCode);
    $frontendClass = $attribute->getData('frontend_class');
    $maxLength = $field->getMaxLength();
    $isDisabled = $block->getIsDisabledOnFrontend();
    ?>

    <div class="field <?php echo $attributeCode; ?><?php if ($field->getFieldRequired()) echo ' required'; ?>">
        <label class="label" for="<?= $block->escapeHtmlAttr($attributeCode) ?>">
            <span>
                <?= $block->escapeHtml(__($attributeLabel)) ?>
            </span>
        </label>
        <div class="control">
            <input type="text"
                <?php if ($maxLength > 0): ?> maxlength="<?php echo $maxLength?>" <?php endif; ?>
                <?php if ($isDisabled): ?> disabled="disabled" <?php endif; ?>
                   id="<?= $block->escapeHtmlAttr($attributeCode) ?>"
                   name="<?= $block->escapeHtmlAttr($attributeCode) ?>"
                   value="<?php echo $value ?>"
                   title="<?= $block->escapeHtmlAttr(__($attributeLabel)) ?>"
                   class="input-text <?php echo $frontendClass; ?><?=
                   $block->escapeHtmlAttr($this->helper('Magento\Customer\Helper\Address')
                       ->getAttributeValidationClass($attributeCode)) ?>"
                <?php if ($field->getFieldRequired()) echo ' data-validate="{required:true}"' ?>>
        </div>
    </div>
<?php endif ?>